/**
 * generate_seed_sql.js
 * ThyroConsult — Generates ready-to-run SQL with properly encrypted PHI
 *
 * Place at: thyroconsult-backend\generate_seed_sql.js
 * Run with: node generate_seed_sql.js > seed_patients.sql
 * Then run:  psql -h localhost -p 5432 -U thyroconsult_user -d thyroconsult -f seed_patients.sql
 */

require('dotenv').config();
const { encryptPHI, hmacHash } = require('./src/utils/encryption');
const bcrypt = require('bcryptjs');

async function main() {
  const doctorId = '96a88ba4-699a-4fdf-b30a-93deebdb229c';
  const passwordHash = await bcrypt.hash('Test@1234!', 12);

  const patients = [
    {
      mobile: '+919823001001', whatsapp: '+919823001001',
      email: 'arun.sharma@test.in',
      firstName: 'Arun', lastName: 'Sharma',
      gender: 'male',
      address: 'Flat 4B Shivaji Nagar', city: 'Pune',
      state: 'Maharashtra', pincode: '411005',
      guardian: null, guardianRelation: null,
    },
    {
      mobile: '+919823001002', whatsapp: '+919823001002',
      email: 'priya.desai@test.in',
      firstName: 'Priya', lastName: 'Desai',
      gender: 'female',
      address: '12 MG Road Vile Parle', city: 'Mumbai',
      state: 'Maharashtra', pincode: '400057',
      guardian: null, guardianRelation: null,
    },
    {
      mobile: '+919823001003', whatsapp: '+919823001003',
      email: 'suresh.nair@test.in',
      firstName: 'Suresh', lastName: 'Nair',
      gender: 'male',
      address: '8 Koregaon Park Lane', city: 'Pune',
      state: 'Maharashtra', pincode: '411001',
      guardian: null, guardianRelation: null,
    },
    {
      mobile: '+919823001004', whatsapp: '+919823001004',
      email: 'meena.iyer@test.in',
      firstName: 'Meena', lastName: 'Iyer',
      gender: 'female',
      address: '3 Anna Salai T Nagar', city: 'Chennai',
      state: 'Tamil Nadu', pincode: '600017',
      guardian: null, guardianRelation: null,
    },
    {
      // Minor patient with guardian
      mobile: '+919823001005', whatsapp: '+919823001005',
      email: 'guardian.ravi@test.in',
      firstName: 'Ravi', lastName: 'Kulkarni',
      gender: 'male',
      address: '22 Deccan Gymkhana', city: 'Pune',
      state: 'Maharashtra', pincode: '411004',
      guardian: 'Ramesh Kulkarni', guardianRelation: 'Father',
    },
  ];

  const lines = [];
  lines.push('-- ThyroConsult Test Patients + Payments Seed');
  lines.push('-- Generated by generate_seed_sql.js');
  lines.push('-- Run: psql -h localhost -p 5432 -U thyroconsult_user -d thyroconsult -f seed_patients.sql');
  lines.push('');
  lines.push('BEGIN;');
  lines.push('');

  const patientIds = [];

  for (let i = 0; i < patients.length; i++) {
    const p = patients[i];
    const pid = `'||uuid_generate_v4()||'`;

    const mobileEnc      = encryptPHI(p.mobile);
    const mobileHmac     = hmacHash(p.mobile);
    const waEnc          = encryptPHI(p.whatsapp);
    const waHmac         = hmacHash(p.whatsapp);
    const emailEnc       = encryptPHI(p.email);
    const emailHmac      = hmacHash(p.email);
    const firstEnc       = encryptPHI(p.firstName);
    const lastEnc        = encryptPHI(p.lastName);
    const addrEnc        = encryptPHI(p.address);
    const cityEnc        = encryptPHI(p.city);
    const stateEnc       = encryptPHI(p.state);
    const pincodeEnc     = encryptPHI(p.pincode);
    const guardianEnc    = p.guardian ? encryptPHI(p.guardian) : 'NULL';
    const guardianRel    = p.guardianRelation ? `'${p.guardianRelation}'` : 'NULL';

    const varName = `v_pid_${i+1}`;
    patientIds.push(varName);

    lines.push(`DO $$`);
    lines.push(`DECLARE ${varName} UUID;`);
    lines.push(`BEGIN`);
    lines.push(`  INSERT INTO patients (`);
    lines.push(`    mobile, mobile_hash, whatsapp, whatsapp_hash,`);
    lines.push(`    email, email_hash, password_hash,`);
    lines.push(`    first_name, last_name, guardian_name, guardian_relation,`);
    lines.push(`    gender, address_line1, city, state, pincode,`);
    lines.push(`    mobile_verified, whatsapp_verified, email_verified,`);
    lines.push(`    registration_step, registration_complete, primary_doctor_id`);
    lines.push(`  ) VALUES (`);
    lines.push(`    '${mobileEnc}', '${mobileHmac}', '${waEnc}', '${waHmac}',`);
    lines.push(`    '${emailEnc}', '${emailHmac}', '${passwordHash}',`);
    lines.push(`    '${firstEnc}', '${lastEnc}', ${guardianEnc === 'NULL' ? 'NULL' : `'${guardianEnc}'`}, ${guardianRel},`);
    lines.push(`    '${p.gender}', '${addrEnc}', '${cityEnc}', '${stateEnc}', '${pincodeEnc}',`);
    lines.push(`    TRUE, TRUE, TRUE,`);
    lines.push(`    7, TRUE, '${doctorId}'`);
    lines.push(`  ) RETURNING id INTO ${varName};`);
    lines.push(``);
    lines.push(`  -- Create appointment`);
    lines.push(`  INSERT INTO appointments (patient_id, doctor_id, scheduled_at, consultation_type, status)`);
    lines.push(`  VALUES (${varName}, '${doctorId}', NOW(), 'video', 'completed');`);
    lines.push(``);
    lines.push(`  -- Create payment`);
    lines.push(`  INSERT INTO payments (`);
    lines.push(`    appointment_id, patient_id, doctor_id,`);
    lines.push(`    razorpay_order_id, razorpay_payment_id, razorpay_signature,`);
    lines.push(`    consultation_fee, platform_fee, gst_amount, total_amount,`);
    lines.push(`    status, payment_method, paid_at`);
    lines.push(`  ) SELECT`);
    lines.push(`    a.id, ${varName}, '${doctorId}',`);
    lines.push(`    'order_TEST${i+1}0${i+1}', 'pay_TEST${i+1}0${i+1}', 'sig_TEST${i+1}',`);
    lines.push(`    1200.00, 50.00, 225.00, 1475.00,`);
    lines.push(`    'confirmed', 'upi', NOW()`);
    lines.push(`  FROM appointments a`);
    lines.push(`  WHERE a.patient_id = ${varName} ORDER BY a.created_at DESC LIMIT 1;`);
    lines.push(``);
    lines.push(`  RAISE NOTICE 'Patient ${i+1} (${p.firstName} ${p.lastName}): %', ${varName};`);
    lines.push(`END;`);
    lines.push(`$$;`);
    lines.push('');
  }

  lines.push('COMMIT;');
  lines.push('');
  lines.push('-- Verify:');
  lines.push(`SELECT p.id, p.patient_code, pay.id AS payment_id, pay.invoice_number`);
  lines.push(`FROM patients p JOIN payments pay ON pay.patient_id = p.id`);
  lines.push(`WHERE pay.razorpay_payment_id LIKE 'pay_TEST%'`);
  lines.push(`ORDER BY p.created_at DESC;`);

  console.log(lines.join('\n'));
}

main().catch(err => {
  console.error('Error:', err.message);
  process.exit(1);
});
